version: '3'

services:
  # app:
  #   image: docker-logs-elk/dummy-app:1.0.0
  #   build:
  #     context: dummy-app
  #     dockerfile: Dockerfile
  #   volumes:
  #    - "/test/log:/test/log"
  #    - "/test1/log:/test1/log"
  #    - "/test2/log:/test2/log"
  #   networks: 
  #     - internal-network
  # filebeat:
  #   hostname: filebeat
  #   image: docker-logs-elk/filebeat:1.0.0
  #   build:
  #     context: filebeat
  #     dockerfile: Dockerfile
  #   volumes:
  #     # needed to access all docker logs (read only) :
  #    - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
  #     # needed to access additional informations about containers
  #    - "/var/run/docker.sock:/var/run/docker.sock"
  #    #For log file
  #    - "/test/log:/test/log"
  #    - "/test1/log:/test1/log"
  #    - "/test2/log:/test2/log"
  #   links:
  #      - logstash
  #   networks: 
  #     - internal-network
      
  kibana:
    image: kibana:6.8.6
    ports:
        - 5601:5601
    restart: always
    networks: 
        - internal-network
  logstash: 
      hostname: logstash 
      image: docker-logs-elk/logstash:1.0.0
      build:
        context: logstash1
        dockerfile: Dockerfile
      ports:
        - 5044:5044
      environment:
        LOG_LEVEL: error
      links:
        - elasticsearch
      networks: 
        - internal-network
      # volumes:
      #     - ./logstash/pipeline:/usr/share/logstash/pipeline
      #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  elasticsearch:
      hostname: elasticsearch
      image: elasticsearch:6.8.6
      ports: 
          - 9200:9200
          - 9300:9300
      restart: always
      networks: 
          - internal-network
      volumes:
          - es-data:/usr/share/elasticsearch/data
      environment:
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - discovery.type=single-node
      
volumes: 
    es-data:
networks: 
    internal-network:
