FROM ubuntu:18.04

CMD while true; do sleep 20 ; echo "{\"app\": \"dummy\", \"foo\": \"bar\"}"; done

CMD while true; do sleep 20 ; echo "{\"type\": \"log\", \"file\": \"test.log\"}" >>/test/log/test.log; done